
#######################################################
###       Dymint Configuration Options     ###
#######################################################
# block production interval
block_time = "2s"
# block production interval in case of no transactions ("0s" produces empty blocks)
max_idle_time = "2m0s"
max_proof_time = "1m40s"
max_supported_batch_skew = 20


# triggers to submit batch to DA and settlement (both required)
batch_submit_max_time = "2m0s"

# max size of batch in bytes that can be accepted by DA
block_batch_max_size_bytes = 50000

### da config ###
da_layer = "celestia" # mock, celestia, avail
namespace_id = "0000000000000000ffff"
# this should be json matching the celestia.Config type
da_config = '{"base_url":"http://light_node:26658","timeout":5000000000,"gas_prices":0.1,"auth_token":"TOKEN","backoff":{"initial_delay":6000000000,"max_delay":6000000000,"growth_factor":2},"retry_attempts":4,"retry_delay":3000000000}'


### p2p config ###

# p2p listen address in the format of /ip4/ip_address/tcp/tcp_port
p2p_listen_address = "/ip4/0.0.0.0/tcp/26656"

# list of nodes used for P2P bootstrapping in the format of /ip4/ip_address/tcp/port/p2p/ID
p2p_bootstrap_nodes = ""

# max number of cached messages by gossipsub protocol
p2p_gossiped_blocks_cache_size = 50

# time interval to check if no p2p nodes are connected to bootstrap again
p2p_bootstrap_retry_time = "30s"

# set to false to disable advertising the node to the P2P network
p2p_advertising_enabled= "true"

#celestia config example:
# da_config = "{\"base_url\":\"http:\/\/127.0.0.1:26658\",\"timeout\":5000000000,\"gas_prices\":0.1,\"auth_token\":\"TOKEN\",\"backoff\":{\"initial_delay\":6000000000,\"max_delay\":6000000000,\"growth_factor\":2},\"retry_attempts\":4,\"retry_delay\":3000000000}"
# Avail config example:
# da_config = "{\"seed\": \"MNEMONIC\", \"api_url\": \"wss://kate.avail.tools/ws\", \"app_id\": 0, \"tip\":10}"

### settlement config ###
settlement_layer = "dymension" # mock, dymension

# dymension config
rollapp_id = "rollappevm_1234-1"
settlement_node_address = "http://dymension:36657"
settlement_gas_limit = 0
settlement_gas_prices = "1000000000adym"
settlement_gas_fees = ""
retry_max_delay = "10s"
retry_min_delay = "1s"
retry_attempts = "10"
batch_acceptance_timeout = "2m0s"
batch_acceptance_attempts = "5"

#keyring and key name to be used for sequencer 
keyring_backend = "test"
keyring_home_dir = "/root/.rollapp/sequencer_keys"
dym_account_name = "sequencer"


#######################################################
###       Instrumentation Configuration Options     ###
#######################################################
[instrumentation]

# When true, Prometheus metrics are served under /metrics on
# PrometheusListenAddr.
# Check out the documentation for the list of available metrics.
prometheus = false

# Address to listen for Prometheus collector(s) connections
prometheus_listen_addr = ":2112"


